### ISSUE TITLE
Group Milestone 1a Submission

### ISSUE THREAD

**Issue by datnguyen92** [ThreeRangers/Tripper#1]
We have already complete these following tasks (except for the survey as we still need to collect the feedbacks):
### Create your organization and project
- [x] Create an organization on Github
- [x] Add each team member in your group to the organization
- [x] Generate a new Xcode project for your group.
- [x] Push the repository to your new project organization.
- [x] Sketch our functional user stories
### Add a README to your project repo with the following elements:
- [x] Paragraph that describes your app and what it does
- [x] Required (core) user stories for your app in a bulleted list
- [x] Optional (nice to have) user stories listed separately
### Research:
- [x] Ask 3 different people for feedback on your idea. Write down their responses and create a document in your GitHub repository with their answers. (still missing the answers)
- Link to the survey: [Travel Planning App Survey](http://www.surveygizmo.com/s3/2479321/Travel-Planning-App-Survey)

/cc @coderschoolreview @minhcasi @Qspace

**Comment by coderschoolreview** [comment]
Great job completing the user stories for the Tripper app, team ThreeRangers! :dancers: 

Besides your your hard work so far, you may want to consider a few caveats. There are a lot of travel apps so far and this topic sounds very cool. However many travel apps don't do well:
- How often does an average person travel? Perhaps only a couple of times a year. Even if they like your app after using once, they may forget about the app next time.
- For each travel destination, a person need to check out my websites, apps, and tourist books to plan for a travel. It is difficult to be the main app for someone to use when they decide to travel to a village, a foreign country or another planet (?) :smiling_imp: 
- People have different travel goals. It is difficult to plan a trip together not because they don't have a good app, but it's because it is difficult for them to agree on the time frames, venues and prices.
- Also because of the above reason, it is difficult to compare destination A vs destination B to make up one's mind.
- People may feel inspired to go to a place due to various reasons, not just because of pretty pics from a listing. Sometimes it takes them days, weeks or even months before they make up their mind. This makes it difficult to provide a full experience in the app.
- If it's a serious business: the main revenue source is from letting users book. I know this is not what you want to do. That's good; this is a very competitive business. However, it's useful to think how your app can make money in theory.

Don't be discouraged by the above if this is still what you want to do. However, if they may you think twice, think twice; it's better to do that early on :) Keep the [product evaluation criteria](http://courses.coderschool.vn/group_project_rough#product-evaluation-criteria) in mind: story, market, habit and scope.

Nevertheless, it's good that you have a focus in your pitch: social travel planning. I get that this can help me invite friends to join you to go somewhere. This is difficult to do using emails or facebook groups because I don't know who will go yet. If I post on Facebook, the post may get buried quickly.

Now:
- Do I have to enter all details about a place I want to go into the app? What's my motivation (find people to travel with me). Can it be easy?
- What happens if I have too many or too few people for the trip? How do I decide who can go and who can't? A group chat can get very noisy very quickly. One-to-one chats can be exhausting. Are you supporting both chat modes? This may be too much for the scope of this project.

Are there any mobile or web apps that are similar to Tripper now? How different are you from them? Why should people use your app?

Check out this tripr app for some similar/overlapping ideas: https://triprapp.com/. They let you create trips and chat with people but it's not for friends to plan to go together but for people to find friends more easily. One of their biggest challenges is that they need to have users before any user can find the app useful (the chicken-and-egg problem). I don't think this app is a good idea because of that challenge, but it has some good UI elements.

On implementation:
- Data:
  - How do you get enough users and trips data to make the app useful for someone when she downloads the app.
  - How will you prepare fake/test data for your app demo on the demo day?
- App:
  - What are your 3 most important screens?
  - What will you use for backend? It's reasonable to expect this app to connect to the internet. Are you using Parse? Any other server side considerations?
  - Do you have a Schema for your app? See this for an example of a mockup flow and the schema for it.
- Are you inspired by any apps? Do you want reuse some UI/UX ideas or animations found in them?

I like the survey questions. Please share what you learn from the survey when you have more data. In the survey, it may be useful to collect optional contact info to follow up with those who would be interested in hearing updates from you.

You already know this, I hope you continue to keep the [Project Overview page[(http://courses.coderschool.vn/group_project_rough) in mind over the next few weeks. Together with your frequent updates on the README file, it will help you focus on what is important and collaborate effectively toward the Demo Day :dart:

**Comment by Qspace** [comment]
Thank you for the really useful feedback. Here are some points:

*_How often does an average person travel? Perhaps only a couple of times a year. Even if they like your app after using once, they may forget about the app next time *_
===>  Actually, an average person only travel 4-5 times a year. But in trippers, we want people has use this app even they don't have a travel plan on a short term. They can view other user plans in , comment on it, share experience and receive notification when the following user has a new plan, upload image ...
Also we think about a story when people using our app for make a charity trip, a picnic trip around the city and make the habit of user for record every trip they make. 
_Maybe we add notification feature when people go to another city (or a far distance from their location on their profile)?_ 

**People have different travel goals. It is difficult to plan a trip together not because they don't have a good app, but it's because it is difficult for them to agree on the time frames, venues and prices**
===> In the beginning, it is difficult to find a group with the same goals. But we think 1-2 persons maybe possibles. And a circumstance, when people have free times in work day, it hard to find partners form their friend, so looking for partners in "Tripper" user may be a good choices.
Also we think about story when tourist guides using our app for make a tour. 
_May be we need information from travel company for make data for app in the beginning?_

**People may feel inspired to go to a place due to various reasons, not just because of pretty pics from a listing. Sometimes it takes them days, weeks or even months before they make up their mind. This makes it difficult to provide a full experience in the app.**
===> We intend to make inspiration for people by notification about other following user trip and reminder them about the trip they make in a past

**If it's a serious business: the main revenue source is from letting users book. I know this is not what you want to do. That's good; this is a very competitive business. However, it's useful to think how your app can make money in theory.**
===> We intend to make money from tourist guides/company. We will think about it when "Trippers" has a large amount of users
/cc @coderschoolreview @minhcasi @Qspace
